"""Stub read-only plant data standing in for Lite's real read-service
layer (see docs/scope.md). A real deployment replaces only this module
(plus services/scoring.py, which is derived from it) - every tool in
tools/ goes through the same records, and no mutating method exists here
or anywhere in this package (BRIDGE-1, SAFE-1, DATA-1).

Two factories, matching the exact grant fixtures the source docs name
(u-ops-alpha -> fx-mbr-01 only, u-ops-beta -> fx-beta-01 only,
services/grants.py::seeded_grant_store):

- fx-mbr-01 (Alpha MBR Plant 01, food_and_beverage): an equalization tank
  feeding a membrane bioreactor. Its story over the 30-day fixture window
  is a slow membrane-fouling arc - TMP climbing, flux declining - that
  eventually correlates with an effluent COD exceedance, so tools 4
  through 8 all have something coherent to say about the same underlying
  event when a caller (or an LLM) walks the arc from score to alert to
  compliance.
- fx-beta-01 (Beta Effluent Plant 01, textiles): an equalization tank
  feeding an activated-sludge basin, mostly stable, with a milder SVI
  trend climbing toward a bulking watch threshold. Everything else stays
  in-band and effluent stays compliant, so this factory reads as the
  "quiet" contrast case.

All series are generated by deterministic closed-form functions of the
day index (see _tmp_series etc. below) rather than random sampling or
hand-typed literals, so the same fixture always produces the same
numbers - the whole point of a "deterministic explanation of why a score
is what it is" ([PRD] Sec 3.1) falls apart if the underlying data isn't
reproducible too.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from datetime import date, timedelta
from typing import Literal

from diagnostic_mcp.models.common import (
    MeasurementType,
    ParameterBand,
    ParameterType,
)

# ---------------------------------------------------------------------------
# Time base
# ---------------------------------------------------------------------------

FIXTURE_TODAY = date(2026, 8, 17)
HISTORY_DAYS = 30
EARLIEST_DATE = FIXTURE_TODAY - timedelta(days=HISTORY_DAYS - 1)


def _date_seq(n: int, end: date = FIXTURE_TODAY) -> list[str]:
    return [(end - timedelta(days=n - 1 - i)).isoformat() for i in range(n)]


DATES_30 = _date_seq(HISTORY_DAYS)
DATES_7 = _date_seq(7)


# ---------------------------------------------------------------------------
# Deterministic series generators
# ---------------------------------------------------------------------------


def _stable(n: int, center: float, amplitude: float, freq: float, decimals: int = 2) -> list[float]:
    return [round(center + amplitude * math.sin(i * freq), decimals) for i in range(n)]


def _tmp_series(n: int = HISTORY_DAYS) -> list[float]:
    """Stable ~21-23 kPa for the first two weeks, then a fouling-style ramp
    up to ~42 kPa - crosses the watch band (>30 kPa) around day 20."""
    values = []
    for i in range(n):
        if i <= 14:
            base = 22 + math.sin(i * 0.6) * 1.2
        else:
            progress = (i - 14) / (n - 1 - 14)
            base = 22 + progress * 20 + math.sin(i * 0.6) * 0.8
        values.append(round(base, 1))
    return values


def _flux_series(n: int = HISTORY_DAYS) -> list[float]:
    """Inversely correlated with TMP - declining flux is the other face of
    the same fouling event, crossing the watch band (<15 LMH) in the same
    window TMP crosses its own."""
    values = []
    for i in range(n):
        if i <= 14:
            base = 24 + math.sin(i * 0.5) * 0.8
        else:
            progress = (i - 14) / (n - 1 - 14)
            base = 24 - progress * 10 + math.sin(i * 0.5) * 0.5
        values.append(round(base, 1))
    return values


def _svi_series(n: int = HISTORY_DAYS) -> list[float]:
    """Stable ~110 mL/g for three weeks, then a milder climb toward the
    bulking watch threshold (150 mL/g), reaching ~165 by the last day."""
    values = []
    for i in range(n):
        if i <= 19:
            base = 110 + math.sin(i * 0.4) * 6
        else:
            progress = (i - 19) / (n - 1 - 19)
            base = 110 + progress * 55 + math.sin(i * 0.4) * 4
        values.append(round(base, 0))
    return values


# fx-mbr-01
TMP_MBR = _tmp_series()
FLUX_MBR = _flux_series()
DO_MBR = _stable(HISTORY_DAYS, center=3.4, amplitude=0.4, freq=0.45)
MLSS_MBR = _stable(HISTORY_DAYS, center=4800, amplitude=250, freq=0.3, decimals=0)
PH_EQ_MBR = _stable(HISTORY_DAYS, center=7.2, amplitude=0.15, freq=0.4)
FLOW_EQ_MBR = _stable(HISTORY_DAYS, center=45, amplitude=4, freq=0.35, decimals=1)

# fx-beta-01
DO_ASP = _stable(HISTORY_DAYS, center=3.0, amplitude=0.3, freq=0.4)
MLSS_ASP = _stable(HISTORY_DAYS, center=4500, amplitude=200, freq=0.28, decimals=0)
SVI_ASP = _svi_series()
PH_EQ_BETA = _stable(HISTORY_DAYS, center=7.0, amplitude=0.2, freq=0.4)
FLOW_EQ_BETA = _stable(HISTORY_DAYS, center=30, amplitude=3, freq=0.3, decimals=1)

# (factory_id, unit_id, parameter_code) -> [(date, value), ...], oldest first
PARAMETER_SERIES: dict[tuple[str, str, str], list[tuple[str, float]]] = {
    ("fx-mbr-01", "u-mbr-01", "tmp"): list(zip(DATES_30, TMP_MBR, strict=True)),
    ("fx-mbr-01", "u-mbr-01", "flux"): list(zip(DATES_30, FLUX_MBR, strict=True)),
    ("fx-mbr-01", "u-mbr-01", "do"): list(zip(DATES_30, DO_MBR, strict=True)),
    ("fx-mbr-01", "u-mbr-01", "mlss"): list(zip(DATES_30, MLSS_MBR, strict=True)),
    ("fx-mbr-01", "u-eq-01", "ph"): list(zip(DATES_30, PH_EQ_MBR, strict=True)),
    ("fx-mbr-01", "u-eq-01", "flow_in"): list(zip(DATES_30, FLOW_EQ_MBR, strict=True)),
    ("fx-beta-01", "u-asp-01", "do"): list(zip(DATES_30, DO_ASP, strict=True)),
    ("fx-beta-01", "u-asp-01", "mlss"): list(zip(DATES_30, MLSS_ASP, strict=True)),
    ("fx-beta-01", "u-asp-01", "svi"): list(zip(DATES_30, SVI_ASP, strict=True)),
    ("fx-beta-01", "u-eq-01", "ph"): list(zip(DATES_30, PH_EQ_BETA, strict=True)),
    ("fx-beta-01", "u-eq-01", "flow_in"): list(zip(DATES_30, FLOW_EQ_BETA, strict=True)),
}

PARAMETER_TYPE: dict[str, ParameterType] = {
    "tmp": "measured",
    "flux": "derived",
    "do": "measured",
    "mlss": "measured",
    "ph": "measured",
    "flow_in": "measured",
    "svi": "measured",
}

# Global reference bands (BRIDGE-3: the thresholds a raw value is
# classified against). Shared across units/factories - a real Lite
# deployment would key some of these per-unit-type or per-plant instead;
# one global table per parameter_code is enough fidelity for this fixture
# set and keeps get_unit_detail, get_parameter_history, get_current_scores
# and explain_score all reading from one source of truth.
PARAMETER_BANDS: dict[str, ParameterBand] = {
    "tmp": ParameterBand(
        parameter_code="tmp", unit="kPa", normal_max=30, watch_max=30, alarm_max=45
    ),
    "flux": ParameterBand(
        parameter_code="flux", unit="LMH", normal_min=15, watch_min=15, alarm_min=10
    ),
    "do": ParameterBand(
        parameter_code="do",
        unit="mg/L",
        normal_min=2.0,
        normal_max=6.0,
        watch_min=2.0,
        watch_max=6.0,
        alarm_min=1.0,
        alarm_max=8.0,
    ),
    "mlss": ParameterBand(
        parameter_code="mlss",
        unit="mg/L",
        normal_min=3000,
        normal_max=6000,
        watch_min=3000,
        watch_max=6000,
        alarm_min=2000,
        alarm_max=8000,
    ),
    "ph": ParameterBand(
        parameter_code="ph",
        unit="pH",
        normal_min=6.5,
        normal_max=8.5,
        watch_min=6.5,
        watch_max=8.5,
        alarm_min=5.5,
        alarm_max=9.5,
    ),
    "flow_in": ParameterBand(
        parameter_code="flow_in",
        unit="m3/h",
        normal_min=15,
        normal_max=70,
        watch_min=10,
        watch_max=80,
        alarm_min=5,
        alarm_max=100,
    ),
    "svi": ParameterBand(
        parameter_code="svi", unit="mL/g", normal_max=150, watch_max=150, alarm_max=200
    ),
}


# ---------------------------------------------------------------------------
# Plant / unit / instrument reference data
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class UnitGeometry:
    volume_m3: float | None
    membrane_area_m2: float | None = None


@dataclass(frozen=True)
class InstrumentRecord:
    instrument_id: str
    parameter_code: str
    measurement_type: MeasurementType


@dataclass(frozen=True)
class UnitRecord:
    unit_id: str
    unit_type: str
    process_qualifiers: tuple[str, ...]
    geometry: UnitGeometry
    instruments: tuple[InstrumentRecord, ...]
    parameter_codes: tuple[str, ...]


@dataclass(frozen=True)
class FlowEdge:
    from_unit_id: str
    to_unit_id: str


@dataclass(frozen=True)
class PlantRecord:
    factory_id: str
    org_id: str
    name: str
    industry: str
    units: tuple[UnitRecord, ...]
    flow: tuple[FlowEdge, ...]
    snapshot_version: str


UNIT_ENGINE: dict[str, str] = {
    "equalization_tank": "hydraulic_buffer_engine",
    "membrane_bioreactor": "membrane_performance_engine",
    "activated_sludge": "biological_process_engine",
}

_PLANTS: dict[str, PlantRecord] = {
    "fx-mbr-01": PlantRecord(
        factory_id="fx-mbr-01",
        org_id="org-alpha",
        name="Alpha MBR Plant 01",
        industry="food_and_beverage",
        units=(
            UnitRecord(
                unit_id="u-eq-01",
                unit_type="equalization_tank",
                process_qualifiers=(),
                geometry=UnitGeometry(volume_m3=220),
                instruments=(
                    InstrumentRecord("ph-probe-01", "ph", "online_sensor"),
                    InstrumentRecord("flow-meter-01", "flow_in", "online_sensor"),
                ),
                parameter_codes=("ph", "flow_in"),
            ),
            UnitRecord(
                unit_id="u-mbr-01",
                unit_type="membrane_bioreactor",
                process_qualifiers=("aerobic",),
                geometry=UnitGeometry(volume_m3=140, membrane_area_m2=1200),
                instruments=(
                    InstrumentRecord("pressure-transducer-01", "tmp", "online_sensor"),
                    InstrumentRecord("flux-calc-01", "flux", "derived"),
                    InstrumentRecord("do-probe-01", "do", "online_sensor"),
                    InstrumentRecord("mlss-analyzer-01", "mlss", "lab_analysis"),
                ),
                parameter_codes=("tmp", "flux", "do", "mlss"),
            ),
        ),
        flow=(FlowEdge("u-eq-01", "u-mbr-01"),),
        snapshot_version="2026-08-17T00:00:00Z",
    ),
    "fx-beta-01": PlantRecord(
        factory_id="fx-beta-01",
        org_id="org-beta",
        name="Beta Effluent Plant 01",
        industry="textiles",
        units=(
            UnitRecord(
                unit_id="u-eq-01",
                unit_type="equalization_tank",
                process_qualifiers=(),
                geometry=UnitGeometry(volume_m3=180),
                instruments=(
                    InstrumentRecord("ph-probe-02", "ph", "online_sensor"),
                    InstrumentRecord("flow-meter-02", "flow_in", "online_sensor"),
                ),
                parameter_codes=("ph", "flow_in"),
            ),
            UnitRecord(
                unit_id="u-asp-01",
                unit_type="activated_sludge",
                process_qualifiers=("aerobic",),
                geometry=UnitGeometry(volume_m3=600),
                instruments=(
                    InstrumentRecord("do-probe-02", "do", "online_sensor"),
                    InstrumentRecord("mlss-analyzer-02", "mlss", "lab_analysis"),
                    InstrumentRecord("svi-lab-01", "svi", "lab_analysis"),
                ),
                parameter_codes=("do", "mlss", "svi"),
            ),
        ),
        flow=(FlowEdge("u-eq-01", "u-asp-01"),),
        snapshot_version="2026-08-17T00:00:00Z",
    ),
}


def get_plant_record(factory_id: str) -> PlantRecord | None:
    return _PLANTS.get(factory_id)


def get_unit_record(factory_id: str, unit_id: str) -> UnitRecord | None:
    plant = get_plant_record(factory_id)
    if plant is None:
        return None
    return next((u for u in plant.units if u.unit_id == unit_id), None)


def get_parameter_series(
    factory_id: str, unit_id: str, parameter_code: str
) -> list[tuple[str, float]] | None:
    return PARAMETER_SERIES.get((factory_id, unit_id, parameter_code))


def get_band(parameter_code: str) -> ParameterBand | None:
    return PARAMETER_BANDS.get(parameter_code)


def get_plant_record_or_raise(factory_id: str) -> PlantRecord:
    """A granted factory_id with no backing record is a data-consistency
    bug (the grant store and the fixture store have drifted), not a
    caller error - authorization already passed by the time any handler
    calls this. Shared by every tool that only needs the plant record
    (plant_overview, current_scores, active_alerts, compliance_status)
    so the same LookupError message isn't hand-copied per tool.
    """
    record = get_plant_record(factory_id)
    if record is None:
        raise LookupError(f"No plant record for granted factory_id={factory_id!r}")
    return record


def get_unit_record_or_raise(factory_id: str, unit_id: str) -> UnitRecord:
    """unit_id isn't itself a security scope (factory_id already carried
    that check via BRIDGE-2), so naming it back to the caller doesn't leak
    anything - unlike an unknown/ungranted factory_id, this is an
    ordinary bad-argument error. Shared by unit_detail, explain_score and
    parameter_history.
    """
    unit = get_unit_record(factory_id, unit_id)
    if unit is None:
        raise LookupError(f"No unit {unit_id!r} for factory {factory_id!r}.")
    return unit


def resolve_as_of(as_of_date: str | None) -> str:
    """Resolve an optional caller-supplied as_of date, defaulting to the
    latest date this fixture set holds.

    Raises ValueError if the caller-supplied date falls outside the range
    this fixture set actually has data for. Silently scoring an
    out-of-range date would otherwise produce contributions=[] and a
    fabricated health_score=100 (see services/scoring.py::score_unit) -
    indistinguishable from a genuinely healthy plant, which is exactly
    the "assume good data" failure BRIDGE-9 exists to prevent elsewhere
    in this codebase (get_parameter_history's record_status). Used by
    get_current_scores and explain_score, the two tools that take an
    as_of_date.
    """
    if as_of_date is None:
        return FIXTURE_TODAY.isoformat()
    parsed = date.fromisoformat(as_of_date)
    if not (EARLIEST_DATE <= parsed <= FIXTURE_TODAY):
        raise ValueError(
            f"as_of_date {as_of_date!r} is outside the range this fixture set holds "
            f"data for ({EARLIEST_DATE.isoformat()} to {FIXTURE_TODAY.isoformat()})."
        )
    return as_of_date


# ---------------------------------------------------------------------------
# Compliance: permit limits vs recent effluent readings
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ComplianceLimitRecord:
    parameter_code: str
    limit_value: float
    unit: str


# fx-mbr-01: COD climbing toward and past its limit in step with the
# membrane-fouling arc above (COD removal efficiency degrades as flux
# drops), ending in an exceedance on the most recent day. BOD stays
# comfortably compliant throughout - not every parameter needs to break.
COD_MBR = [195.0, 202.0, 198.0, 210.0, 225.0, 248.0, 265.0]
BOD_MBR = [18.0, 19.0, 18.0, 20.0, 21.0, 22.0, 22.0]

# fx-beta-01: both effluent parameters stay well inside their limits.
COD_BETA = [150.0, 155.0, 148.0, 160.0, 158.0, 152.0, 161.0]
BOD_BETA = [20.0, 21.0, 19.0, 22.0, 21.0, 20.0, 21.0]

COMPLIANCE_LIMITS: dict[str, list[ComplianceLimitRecord]] = {
    "fx-mbr-01": [
        ComplianceLimitRecord("cod", 250.0, "mg/L"),
        ComplianceLimitRecord("bod", 30.0, "mg/L"),
    ],
    "fx-beta-01": [
        ComplianceLimitRecord("cod", 200.0, "mg/L"),
        ComplianceLimitRecord("bod", 30.0, "mg/L"),
    ],
}

EFFLUENT_READINGS: dict[tuple[str, str], list[tuple[str, float]]] = {
    ("fx-mbr-01", "cod"): list(zip(DATES_7, COD_MBR, strict=True)),
    ("fx-mbr-01", "bod"): list(zip(DATES_7, BOD_MBR, strict=True)),
    ("fx-beta-01", "cod"): list(zip(DATES_7, COD_BETA, strict=True)),
    ("fx-beta-01", "bod"): list(zip(DATES_7, BOD_BETA, strict=True)),
}


# ---------------------------------------------------------------------------
# Alerts: deterministic rule firings with root-cause hints
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AlertRecord:
    alert_id: str
    factory_id: str
    unit_id: str | None
    parameter_code: str | None
    rule_name: str
    severity: Literal["info", "warning", "critical"]
    fired_at: str
    status: Literal["active", "resolved"]
    root_cause_hint: str
    trigger_value: float | None
    trigger_unit: str | None


def _series_value_at(factory_id: str, unit_id: str, parameter_code: str, iso_date: str) -> float:
    series = PARAMETER_SERIES[(factory_id, unit_id, parameter_code)]
    return next(v for d, v in series if d == iso_date)


ALERTS: dict[str, list[AlertRecord]] = {
    "fx-mbr-01": [
        AlertRecord(
            alert_id="al-mbr-tmp-01",
            factory_id="fx-mbr-01",
            unit_id="u-mbr-01",
            parameter_code="tmp",
            rule_name="TMP_RISING_RULE",
            severity="warning",
            # Index 21, not 20: 21 is the first day TMP actually reads above
            # watch_max (31.4 kPa); index 20 (29.6 kPa) is still "normal", and
            # firing the alert there would contradict get_parameter_history /
            # get_current_scores for that same date and parameter.
            fired_at=f"{DATES_30[21]}T06:00:00Z",
            status="active",
            root_cause_hint=(
                "Progressive TMP rise alongside declining flux over the last two "
                "weeks is consistent with membrane fouling; check CIP/backwash "
                "schedule adherence before assuming an instrument fault."
            ),
            trigger_value=_series_value_at("fx-mbr-01", "u-mbr-01", "tmp", DATES_30[21]),
            trigger_unit="kPa",
        ),
        AlertRecord(
            alert_id="al-mbr-cod-01",
            factory_id="fx-mbr-01",
            # Not unit-scoped: COD is a plant-level effluent/compliance
            # parameter (get_compliance_status), not one of u-mbr-01's
            # tracked instrument parameters - it has no band or series of its
            # own, so naming a unit_id here would point a caller at
            # get_unit_detail/get_parameter_history for something neither
            # tool can resolve.
            unit_id=None,
            parameter_code="cod",
            rule_name="COD_LIMIT_EXCEEDANCE_RULE",
            severity="critical",
            fired_at=f"{DATES_7[-1]}T06:00:00Z",
            status="active",
            root_cause_hint=(
                "Effluent COD exceeded the permit limit on the same day flux "
                "reached its lowest point in the window; treat membrane "
                "performance loss as the primary hypothesis before considering "
                "dilution or bypass changes."
            ),
            trigger_value=COD_MBR[-1],
            trigger_unit="mg/L",
        ),
    ],
    "fx-beta-01": [
        AlertRecord(
            alert_id="al-beta-svi-01",
            factory_id="fx-beta-01",
            unit_id="u-asp-01",
            parameter_code="svi",
            rule_name="SVI_TREND_WATCH_RULE",
            severity="warning",
            # Index 28, not 26: 28 is the first day SVI actually reads above
            # watch_max (156 mL/g; 150 exactly is still "normal" - the
            # boundary is exclusive). Firing earlier would contradict
            # get_parameter_history for that same date and parameter.
            fired_at=f"{DATES_30[28]}T06:00:00Z",
            status="active",
            root_cause_hint=(
                "SVI is trending toward the bulking threshold while MLSS and DO "
                "remain stable, suggesting an emerging filamentous bulking risk "
                "rather than a loading change; check F/M ratio and DO "
                "distribution before adjusting the wasting rate."
            ),
            trigger_value=_series_value_at("fx-beta-01", "u-asp-01", "svi", DATES_30[28]),
            trigger_unit="mL/g",
        ),
    ],
}


def get_alerts(factory_id: str) -> list[AlertRecord]:
    return ALERTS.get(factory_id, [])
